version: "3"

networks:
  monitoring:
    external:
      name: monitoring

services:
  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: donex_prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    links:
    - cadvisor:cadvisor
    depends_on:
      - cadvisor
    networks:
      - monitoring
    restart: always
    labels:
      org.label-schema.group: "monitoring"

  prometheusexporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    ports:
    - "9113:9113"
    environment: 
    - NP_EXPORTER=${NP_EXPORTER}
    entrypoint:
    - /usr/bin/exporter
    - -nginx.scrape-uri
    - http://${NP_EXPORTER}/metrics
    container_name: donex_nginx_prometheus

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: donex_nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring
    restart: always
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: donex_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - monitoring
    restart: always
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:7.3.4
    container_name: donex_grafana
    depends_on:
      - prometheus
    container_name: donex_grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./certs/full-fullchain.pem:/etc/ssl/full-fullchain.pem
      - ./certs/full-privkey.pem:/etc/ssl/full-privkey.pem
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GRAFANA_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
  
  nginx: 
    image: nginx:latest
    container_name: donex_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/full-fullchain.pem:/etc/ssl/full-fullchain.pem
      - ./certs/full-privkey.pem:/etc/ssl/full-privkey.pem
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes: 
  grafana_data:
  prometheus_data: