{
 "title": "nginx",
 "description": "https://github.com/nginxinc/nginx-prometheus-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "项目",
    "query": "label_values(nginx_up, project)"
   },
   {
    "name": "server",
    "label": "主机",
    "query": "label_values(nginx_up{project=~\"$project\"}, server)"
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(nginx_up{project=~\"$project\",server=~\"$server\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{project=~\"$project\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "nginx_connections_reading{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "reading"
    },
    {
     "expr": "nginx_connections_waiting{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "waiting"
    },
    {
     "expr": "nginx_connections_writing{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "total requests"
    }
   ]
  }
 ]
}