{
 "title": "donexpress Log Metrics",
 "description": "NGINX Log metrics with Prometheus based on https://www.martin-helmich.de/en/blog/monitoring-nginx.html. Based on namespace prefix 'nginx'. If different, you may need to adjust the metrics.",
 "tags": [
  "donexpress",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(donexpress_http_response_time_seconds_sum[5m])) by (instance) / sum(rate(donexpress_http_response_time_seconds_count[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(donexpress_http_response_time_seconds_count[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Response time (90% quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "donexpress_http_response_time_seconds{quantile=\"0.9\",method=\"GET\",status=~\"2[0-9]*\"}"
    }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "graph",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(donexpress_http_response_size_bytes[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(donexpress_http_response_count_total[1m])) by (status)"
    }
   ]
  }
 ]
}